#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
feh --bg-fill --no-fehbg ~/.wallpapers/w1.jpg
dunst
$HOME/.config/.scripts/mouse.sh "Stealserias" 2.5
picom
$HOME/.config/.scripts/bar.sh

bspc monitor HDMI-0 -d I II III IV V VI VII VIII IX X
xrandr --output HDMI-0 --mode 2560x1440 --rate 60

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
