#!/bin/sh
# sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &
# dunst
/usr/bin/dunst &
# flameshot
flameshot &
# polybar
polybar &

xrandr --output HDMI-1 --mode 2560x1440 --rate 60.00 --rotate normal

bspc monitor -d 1 2 3 4 5 6 7  

bspc config border_radius		10
bspc config border_width        2
bspc config window_gap          10

bspc config top_padding			-5
bspc config bottom_padding		0
bspc config left_padding		0
bspc config right_config		0

bspc config focus_follow_pointer true
bspc config split_ratio			0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config normal_border_color "#9caca4"
bspc config active_border_color "#F3B3A7"
bspc config focused_border_color "#CFFFE9"
bspc config presel_feedback_color "#FFA79E"

bspc rule -a Steam desktop='^5' state=floating
bspc rule -a Krita desktop='^4' state=floating follow=on
bspc rule -a Librewolf desktop='^3' state=floating
bspc rule -a alacritty state=floating
